idf_component_register(
    SRCS
        "main.c"
        "i2c_bus.c"
        "tca9548a.c"
        "generic_sensor.c"
        "port_manager.c"
        "sd_card.c"
        "nvs_config.c"
        "wifi_manager.c"
        "sensor_task.c"
        "logger_task.c"
        "telemetry_task.c"
        "web_server.c"
        "sht30.c"
        "bme280.c"
        "hih6130.c"
        "te.c"
    INCLUDE_DIRS
        "."
    EMBED_TXTFILES
        "web/index.html"
        "web/style.css.gz"
        "web/app.js.gz"
    EMBED_FILES
        "web/left.png"
        "web/right.png"
    REQUIRES
        driver
        nvs_flash
        esp_wifi
        esp_http_server
        fatfs
        esp_netif
        freertos
        log
        json
        esp_timer
        esp_event
        spi_flash
        sdmmc
)
